// <auto-generated />
using System;
using GiftCardPlatform.Modules.Distribution.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Distribution.Infrastructure.Migrations
{
    [DbContext(typeof(DistributionDbContext))]
    [Migration("20260728055338_AddCardholderDistributionHistoryRead")]
    partial class AddCardholderDistributionHistoryRead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("distribution")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.BulkGiftCardBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("batch_reference");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("intent_hash")
                        .IsFixedLength();

                    b.Property<Guid>("IssuingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_organization_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FundingOrganizationId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_bulk_batch_tenant_idempotency");

                    b.HasIndex("IssuingOrganizationId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_distribution_bulk_batch_history");

                    b.ToTable("bulk_batches", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_distribution_bulk_batches_completion", "\"completed_at_utc\" IS NULL\nOR \"completed_at_utc\" >= \"created_at_utc\"");

                            t.HasCheckConstraint("ck_distribution_bulk_batches_state", "(\"state\" = 'Processing' AND \"completed_at_utc\" IS NULL)\nOR\n(\"state\" = 'Completed' AND \"completed_at_utc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_distribution_bulk_batches_total_items", "\"total_items\" between 1 and 100");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.BulkGiftCardBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("contact_type");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("DistributedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distributed_at_utc");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<string>("GiftCardPublicReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gift_card_public_reference");

                    b.Property<string>("GiftCardState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gift_card_state");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<string>("InvitationState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("invitation_state");

                    b.Property<Guid>("IssuingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_organization_id");

                    b.Property<string>("ItemReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("item_reference");

                    b.Property<string>("MaskedRecipientContact")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("masked_recipient_contact");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_bulk_item_card");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_bulk_item_invitation");

                    b.HasIndex("BatchId", "ItemReference")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_bulk_item_reference");

                    b.HasIndex("BatchId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_bulk_item_position");

                    b.ToTable("bulk_items", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_distribution_bulk_items_amount", "\"amount\" > 0");

                            t.HasCheckConstraint("ck_distribution_bulk_items_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_distribution_bulk_items_position", "\"position\" > 0");

                            t.HasCheckConstraint("ck_distribution_bulk_items_result_states", "\"gift_card_state\" = 'AwaitingClaim'\nAND \"invitation_state\" = 'Pending'");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.DistributionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_distribution_events_card_history");

                    b.HasIndex("InvitationId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_distribution_events_invitation_history");

                    b.ToTable("events", "distribution");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.DistributionInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("business_reference");

                    b.Property<DateTimeOffset>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at_utc");

                    b.Property<string>("ClaimIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("claim_idempotency_key");

                    b.Property<string>("ClaimSecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("claim_secret_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("contact_type");

                    b.Property<DateTimeOffset>("DistributedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distributed_at_utc");

                    b.Property<Guid>("DistributedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributed_by_membership_id");

                    b.Property<Guid>("DistributedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributed_by_user_id");

                    b.Property<int>("FailedClaimAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_claim_attempts");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool?>("IdentityWasCreatedOnClaim")
                        .HasColumnType("boolean")
                        .HasColumnName("identity_was_created_on_claim");

                    b.Property<Guid>("IssuingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_organization_id");

                    b.Property<string>("MaskedRecipientContact")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("masked_recipient_contact");

                    b.Property<string>("RecipientContact")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_contact");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_gift_card")
                        .HasFilter("\"state\" = 'Pending'");

                    b.HasIndex("ClaimedByUserId", "ClaimedAtUtc")
                        .HasDatabaseName("ix_distribution_identity_history")
                        .HasFilter("\"claimed_by_user_id\" IS NOT NULL");

                    b.HasIndex("FundingOrganizationId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_distribution_tenant_idempotency");

                    b.HasIndex("IssuingOrganizationId", "DistributedAtUtc", "Id")
                        .HasDatabaseName("ix_distribution_organization_history");

                    b.ToTable("invitations", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_distribution_invitations_contact_type", "\"contact_type\" in ('Email', 'Phone')");

                            t.HasCheckConstraint("ck_distribution_invitations_expiry", "\"claim_expires_at_utc\" > \"distributed_at_utc\"");

                            t.HasCheckConstraint("ck_distribution_invitations_failed_attempts", "\"failed_claim_attempts\" >= 0");

                            t.HasCheckConstraint("ck_distribution_invitations_state", "(\"state\" = 'Pending'\n    AND \"claimed_by_user_id\" IS NULL\n    AND \"claimed_at_utc\" IS NULL\n    AND \"claim_idempotency_key\" IS NULL\n    AND \"identity_was_created_on_claim\" IS NULL)\nOR\n(\"state\" = 'Claimed'\n    AND \"claimed_by_user_id\" IS NOT NULL\n    AND \"claimed_at_utc\" IS NOT NULL\n    AND \"claim_idempotency_key\" IS NOT NULL\n    AND \"identity_was_created_on_claim\" IS NOT NULL)\nOR\n(\"state\" IN ('Locked', 'Expired', 'Cancelled')\n    AND \"claimed_by_user_id\" IS NULL\n    AND \"claimed_at_utc\" IS NULL\n    AND \"claim_idempotency_key\" IS NULL\n    AND \"identity_was_created_on_claim\" IS NULL)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.BulkGiftCardBatchItem", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Distribution.Domain.BulkGiftCardBatch", null)
                        .WithMany("Items")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.DistributionEvent", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Distribution.Domain.DistributionInvitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Distribution.Domain.BulkGiftCardBatch", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
