// <auto-generated />
using System;
using GiftCardPlatform.Modules.Partners.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Partners.Infrastructure.Migrations
{
    [DbContext(typeof(PartnersDbContext))]
    [Migration("20260824094314_AddPartnerMintRateWindows")]
    partial class AddPartnerMintRateWindows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("partners")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Partners.Domain.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<Guid>("RootOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_partners_code");

                    b.HasIndex("RootOrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_partners_root_organization");

                    b.ToTable("partners", "partners", t =>
                        {
                            t.HasCheckConstraint("ck_partners_code", "\"code\" ~ '^[A-Z0-9-]+$'");

                            t.HasCheckConstraint("ck_partners_status", "(\"status\" = 'Active' AND \"disabled_at_utc\" IS NULL)\nOR\n(\"status\" = 'Disabled' AND \"disabled_at_utc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Partners.Domain.PartnerApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<Guid>("RootOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_organization_id");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_partner_api_clients_code");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_partner_api_clients_partner");

                    b.ToTable("api_clients", "partners", t =>
                        {
                            t.HasCheckConstraint("ck_partner_api_clients_code", "\"code\" ~ '^[A-Z0-9-]+$'");

                            t.HasCheckConstraint("ck_partner_api_clients_scopes", "cardinality(\"scopes\") >= 1");

                            t.HasCheckConstraint("ck_partner_api_clients_secret_hash", "\"secret_hash\" ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_partner_api_clients_status", "(\"status\" = 'Active' AND \"disabled_at_utc\" IS NULL)\nOR\n(\"status\" = 'Disabled' AND \"disabled_at_utc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Partners.Infrastructure.PartnerMintRateWindow", b =>
                {
                    b.Property<Guid>("PartnerApiClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_api_client_id");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer")
                        .HasColumnName("request_count");

                    b.Property<DateTimeOffset>("WindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_started_at_utc");

                    b.HasKey("PartnerApiClientId");

                    b.ToTable("mint_rate_windows", "partners", t =>
                        {
                            t.HasCheckConstraint("ck_partner_mint_rate_windows_request_count", "request_count > 0");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Partners.Domain.PartnerApiClient", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Partners.Domain.Partner", null)
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Partners.Infrastructure.PartnerMintRateWindow", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Partners.Domain.PartnerApiClient", null)
                        .WithMany()
                        .HasForeignKey("PartnerApiClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
