// <auto-generated />
using System;
using GiftCardPlatform.Modules.Authorization.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Authorization.Infrastructure.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    [Migration("20260724110100_InitialAuthorization")]
    partial class InitialAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authorization")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.MembershipRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnchorOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("anchor_organization_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_type");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("ix_membership_role_assignments_membership_id");

                    b.HasIndex("RoleId");

                    b.HasIndex("MembershipId", "RoleId", "AnchorOrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_membership_role_assignments_membership_role_anchor");

                    b.ToTable("membership_role_assignments", "authorization");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.MembershipRoleAssignmentScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GrantedOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_organization_id");

                    b.Property<Guid>("MembershipRoleAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_role_assignment_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("MembershipRoleAssignmentId", "GrantedOrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_assignment_scopes_assignment_organization");

                    b.ToTable("membership_role_assignment_scopes", "authorization");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.PermissionDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("IsPlatformPermission")
                        .HasColumnType("boolean")
                        .HasColumnName("is_platform_permission");

                    b.HasKey("Name");

                    b.ToTable("permissions", "authorization");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_organization_name");

                    b.ToTable("roles", "authorization");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Permission");

                    b.HasIndex("RoleId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ux_role_permissions_role_permission");

                    b.ToTable("role_permissions", "authorization");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.MembershipRoleAssignment", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Authorization.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.MembershipRoleAssignmentScope", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Authorization.Domain.MembershipRoleAssignment", null)
                        .WithMany("SelectedOrganizations")
                        .HasForeignKey("MembershipRoleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.RolePermission", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Authorization.Domain.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("Permission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiftCardPlatform.Modules.Authorization.Domain.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.MembershipRoleAssignment", b =>
                {
                    b.Navigation("SelectedOrganizations");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Authorization.Domain.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
