// <auto-generated />
using System;
using GiftCardPlatform.Modules.Sharing.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Sharing.Infrastructure.Migrations
{
    [DbContext(typeof(SharingDbContext))]
    partial class SharingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sharing")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Sharing.Domain.GiftCardShare", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("CancelIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cancel_idempotency_key");

                    b.Property<Guid?>("ChildGiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_gift_card_id");

                    b.Property<string>("ClaimIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("claim_idempotency_key");

                    b.Property<string>("ClaimSecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("claim_secret_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("CreateIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("create_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_pin_attempts");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<bool?>("IdentityWasCreatedOnClaim")
                        .HasColumnType("boolean")
                        .HasColumnName("identity_was_created_on_claim");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("MaskedRecipientContact")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("masked_recipient_contact");

                    b.Property<string>("PinHash")
                        .HasMaxLength(104)
                        .HasColumnType("character varying(104)")
                        .HasColumnName("pin_hash");

                    b.Property<string>("RecipientContact")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_contact");

                    b.Property<string>("RecipientContactType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("recipient_contact_type");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<Guid>("SourceGiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_gift_card_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ChildGiftCardId")
                        .IsUnique()
                        .HasDatabaseName("ux_sharing_child_card")
                        .HasFilter("\"child_gift_card_id\" IS NOT NULL");

                    b.HasIndex("LedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_sharing_ledger_transaction")
                        .HasFilter("\"ledger_transaction_id\" IS NOT NULL");

                    b.HasIndex("SenderUserId", "CreateIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_sharing_sender_idempotency");

                    b.HasIndex("SourceGiftCardId", "State")
                        .HasDatabaseName("ix_sharing_source_active");

                    b.HasIndex("ClaimedByUserId", "ClaimedAtUtc", "Id")
                        .HasDatabaseName("ix_sharing_recipient_history")
                        .HasFilter("\"claimed_by_user_id\" IS NOT NULL");

                    b.HasIndex("SenderUserId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_sharing_sender_history");

                    b.HasIndex("State", "ExpiresAtUtc", "Id")
                        .HasDatabaseName("ix_sharing_expiration");

                    b.ToTable("shares", "sharing", t =>
                        {
                            t.HasCheckConstraint("ck_sharing_amount", "\"amount\" > 0");

                            t.HasCheckConstraint("ck_sharing_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_sharing_expiry", "\"expires_at_utc\" > \"created_at_utc\"");

                            t.HasCheckConstraint("ck_sharing_failed_attempts", "\"failed_pin_attempts\" >= 0");

                            t.HasCheckConstraint("ck_sharing_kind", "(\"kind\" = 'ProtectedLink'\r\n    AND \"pin_hash\" IS NOT NULL\r\n    AND \"recipient_contact_type\" IS NULL\r\n    AND \"recipient_contact\" IS NULL\r\n    AND \"masked_recipient_contact\" IS NULL)\r\nOR\r\n(\"kind\" = 'DirectInvitation'\r\n    AND \"pin_hash\" IS NULL\r\n    AND \"recipient_contact_type\" IN ('Email', 'Phone')\r\n    AND \"recipient_contact\" IS NOT NULL\r\n    AND \"masked_recipient_contact\" IS NOT NULL\r\n    AND \"failed_pin_attempts\" = 0)");

                            t.HasCheckConstraint("ck_sharing_state", "(\"state\" = 'Pending'\r\n    AND \"claimed_by_user_id\" IS NULL\r\n    AND \"child_gift_card_id\" IS NULL\r\n    AND \"ledger_transaction_id\" IS NULL\r\n    AND \"claim_idempotency_key\" IS NULL\r\n    AND \"identity_was_created_on_claim\" IS NULL\r\n    AND \"claimed_at_utc\" IS NULL\r\n    AND \"closed_at_utc\" IS NULL)\r\nOR\r\n(\"state\" = 'Claiming'\r\n    AND \"claimed_by_user_id\" IS NOT NULL\r\n    AND \"child_gift_card_id\" IS NOT NULL\r\n    AND \"ledger_transaction_id\" IS NOT NULL\r\n    AND \"claim_idempotency_key\" IS NOT NULL\r\n    AND \"identity_was_created_on_claim\" IS NULL\r\n    AND \"claimed_at_utc\" IS NULL\r\n    AND \"closed_at_utc\" IS NULL)\r\nOR\r\n(\"state\" = 'Claimed'\r\n    AND \"claimed_by_user_id\" IS NOT NULL\r\n    AND \"child_gift_card_id\" IS NOT NULL\r\n    AND \"ledger_transaction_id\" IS NOT NULL\r\n    AND \"claim_idempotency_key\" IS NOT NULL\r\n    AND ((\"kind\" = 'ProtectedLink' AND \"identity_was_created_on_claim\" IS NULL)\r\n         OR (\"kind\" = 'DirectInvitation' AND \"identity_was_created_on_claim\" IS NOT NULL))\r\n    AND \"claimed_at_utc\" IS NOT NULL\r\n    AND \"closed_at_utc\" IS NOT NULL)\r\nOR\r\n(\"state\" IN ('Cancelled', 'Expired', 'Locked')\r\n    AND \"claimed_by_user_id\" IS NULL\r\n    AND \"child_gift_card_id\" IS NULL\r\n    AND \"ledger_transaction_id\" IS NULL\r\n    AND \"claim_idempotency_key\" IS NULL\r\n    AND \"identity_was_created_on_claim\" IS NULL\r\n    AND \"claimed_at_utc\" IS NULL\r\n    AND \"closed_at_utc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Sharing.Domain.GiftCardShareEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("event_type");

                    b.HasKey("Id");

                    b.HasIndex("ShareId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_sharing_events_history");

                    b.ToTable("events", "sharing");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Sharing.Domain.GiftCardShareEvent", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Sharing.Domain.GiftCardShare", null)
                        .WithMany()
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
