// <auto-generated />
using GiftCardPlatform.Modules.Audit.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GiftCardPlatform.Modules.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260727140005_AddTenantIsolationAndMembershipAttribution")]
    partial class AddTenantIsolationAndMembershipAttribution
    {
    }
}
