// <auto-generated />
using System;
using GiftCardPlatform.Modules.Audit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260728054324_AddAuditInvestigationIndex")]
    partial class AddAuditInvestigationIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation");

                    b.Property<Guid?>("OrganizationScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_scope_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.HasKey("Id");

                    b.HasIndex("ActorMembershipId")
                        .HasDatabaseName("ix_audit_records_actor_membership_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_occurred_at_utc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_records_entity");

                    b.HasIndex("OrganizationScopeId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_audit_records_organization_history");

                    b.ToTable("audit_records", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
