// <auto-generated />
using System;
using GiftCardPlatform.Modules.Audit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("audit_record_sequence", "audit");

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("FirstSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("first_sequence");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("format_version");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hash_algorithm");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<byte[]>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("manifest_digest");

                    b.Property<byte[]>("MerkleRoot")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("merkle_root");

                    b.Property<Guid?>("PreviousCheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_checkpoint_id");

                    b.Property<byte[]>("PreviousManifestDigest")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_manifest_digest");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.HasKey("Id");

                    b.HasIndex("LastSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_checkpoints_last_sequence");

                    b.HasIndex("ManifestDigest")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_checkpoints_manifest_digest");

                    b.HasIndex("PreviousCheckpointId")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_checkpoints_previous_id");

                    b.ToTable("audit_checkpoints", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_checkpoint_digest_length", "octet_length(manifest_digest) = 32");

                            t.HasCheckConstraint("ck_audit_checkpoint_previous_digest_length", "previous_manifest_digest IS NULL OR octet_length(previous_manifest_digest) = 32");

                            t.HasCheckConstraint("ck_audit_checkpoint_record_count", "record_count > 0");

                            t.HasCheckConstraint("ck_audit_checkpoint_root_length", "octet_length(merkle_root) = 32");

                            t.HasCheckConstraint("ck_audit_checkpoint_sequence", "first_sequence > 0 AND last_sequence >= first_sequence");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpointSeal", b =>
                {
                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.Property<DateTimeOffset>("SignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at_utc");

                    b.HasKey("CheckpointId");

                    b.ToTable("audit_checkpoint_seals", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_checkpoint_public_key", "octet_length(public_key) > 0");

                            t.HasCheckConstraint("ck_audit_checkpoint_signature", "octet_length(signature) = 64");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpointWitness", b =>
                {
                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<byte[]>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("manifest_digest");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("WitnessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("witnessed_at_utc");

                    b.HasKey("CheckpointId");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_checkpoint_witness_reference");

                    b.ToTable("audit_checkpoint_witnesses", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_witness_digest_length", "octet_length(manifest_digest) = 32");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation");

                    b.Property<Guid?>("OrganizationScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_scope_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_sequence")
                        .HasDefaultValueSql("nextval('audit.audit_record_sequence')");

                    b.HasKey("Id");

                    b.HasIndex("ActorMembershipId")
                        .HasDatabaseName("ix_audit_records_actor_membership_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_occurred_at_utc");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_records_sequence");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_records_entity");

                    b.HasIndex("OrganizationScopeId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_audit_records_organization_history");

                    b.ToTable("audit_records", "audit");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpointSeal", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpoint", null)
                        .WithOne()
                        .HasForeignKey("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpointSeal", "CheckpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpointWitness", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpoint", null)
                        .WithOne()
                        .HasForeignKey("GiftCardPlatform.Modules.Audit.Domain.AuditCheckpointWitness", "CheckpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
