// <auto-generated />
using System;
using GiftCardPlatform.Modules.Organizations.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Organizations.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260724075229_AddOptimisticConcurrencyTokens")]
    partial class AddOptimisticConcurrencyTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizations")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Organizations.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("HierarchyPath")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("hierarchy_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_organization_id");

                    b.Property<Guid>("RootOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_root_code")
                        .HasFilter("parent_organization_id IS NULL");

                    b.HasIndex("HierarchyPath")
                        .HasDatabaseName("ix_organizations_hierarchy_path");

                    b.HasIndex("ParentOrganizationId")
                        .HasDatabaseName("ix_organizations_parent_organization_id");

                    b.HasIndex("RootOrganizationId")
                        .HasDatabaseName("ix_organizations_root_organization_id");

                    b.HasIndex("RootOrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_tenant_code")
                        .HasFilter("parent_organization_id IS NOT NULL");

                    b.ToTable("organizations", "organizations", t =>
                        {
                            t.HasCheckConstraint("ck_organizations_depth_non_negative", "\"depth\" >= 0");

                            t.HasCheckConstraint("ck_organizations_max_depth", "\"depth\" <= 4");

                            t.HasCheckConstraint("ck_organizations_no_self_parent", "\"parent_organization_id\" IS NULL OR \"parent_organization_id\" <> \"id\"");

                            t.HasCheckConstraint("ck_organizations_root_depth", "(\"parent_organization_id\" IS NULL AND \"depth\" = 0) OR (\"parent_organization_id\" IS NOT NULL AND \"depth\" > 0)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_memberships_organization_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_organization_memberships_organization_user");

                    b.ToTable("organization_memberships", "organizations");
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Organizations.Domain.Organization", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("ParentOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
