// <auto-generated />
using GiftCardPlatform.Modules.Organizations.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GiftCardPlatform.Modules.Organizations.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationsDbContext))]
    [Migration("20260727140000_AlignHierarchyTenantBoundary")]
    partial class AlignHierarchyTenantBoundary
    {
    }
}
