// <auto-generated />
using System;
using GiftCardPlatform.Modules.GiftCards.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.GiftCards.Infrastructure.Migrations
{
    [DbContext(typeof(GiftCardsDbContext))]
    [Migration("20260727132154_AddDistributionOwnershipState")]
    partial class AddDistributionOwnershipState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gift_cards")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("business_reference");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DistributedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distributed_at_utc");

                    b.Property<Guid?>("DistributionInvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_invitation_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("InitialValue")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("initial_value");

                    b.Property<bool>("IsDivisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_divisible");

                    b.Property<bool>("IsTransferable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_transferable");

                    b.Property<Guid>("IssuanceLedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuance_ledger_transaction_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("IssuedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_membership_id");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<Guid>("IssuingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_organization_id");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid?>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_organization_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("OwnershipState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ownership_state");

                    b.Property<string>("PublicReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("public_reference");

                    b.Property<Guid>("RootGiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_gift_card_id");

                    b.Property<Guid?>("SourceGiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_gift_card_id");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DistributionInvitationId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_distribution_invitation")
                        .HasFilter("\"distribution_invitation_id\" IS NOT NULL");

                    b.HasIndex("IssuanceLedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_issuance_transaction");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_ledger_account");

                    b.HasIndex("PublicReference")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_public_reference");

                    b.HasIndex("SourceGiftCardId")
                        .HasDatabaseName("ix_gift_cards_source")
                        .HasFilter("\"source_gift_card_id\" IS NOT NULL");

                    b.HasIndex("FundingOrganizationId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_tenant_idempotency");

                    b.HasIndex("RootGiftCardId", "Generation")
                        .HasDatabaseName("ix_gift_cards_root_generation");

                    b.HasIndex("OwnerUserId", "IssuedAtUtc", "Id")
                        .HasDatabaseName("ix_gift_cards_identity_owner")
                        .HasFilter("\"owner_user_id\" IS NOT NULL");

                    b.HasIndex("OwnerOrganizationId", "OwnershipState", "IssuedAtUtc", "Id")
                        .HasDatabaseName("ix_gift_cards_organization_inventory");

                    b.ToTable("gift_cards", "gift_cards", t =>
                        {
                            t.HasCheckConstraint("ck_gift_cards_amount", "\"initial_value\" > 0");

                            t.HasCheckConstraint("ck_gift_cards_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_gift_cards_distribution_state", "(\"ownership_state\" = 'OrganizationInventory'\n    AND \"distribution_invitation_id\" IS NULL\n    AND \"distributed_at_utc\" IS NULL\n    AND \"claimed_at_utc\" IS NULL)\nOR\n(\"ownership_state\" = 'AwaitingClaim'\n    AND \"lifecycle_state\" = 'AwaitingClaim'\n    AND \"distribution_invitation_id\" IS NOT NULL\n    AND \"distributed_at_utc\" IS NOT NULL\n    AND \"claimed_at_utc\" IS NULL)\nOR\n(\"ownership_state\" = 'IdentityOwned'\n    AND \"distribution_invitation_id\" IS NOT NULL\n    AND \"distributed_at_utc\" IS NOT NULL\n    AND \"claimed_at_utc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_gift_cards_ownership", "(\"ownership_state\" = 'OrganizationInventory'\n    AND \"owner_organization_id\" IS NOT NULL\n    AND \"owner_user_id\" IS NULL)\nOR\n(\"ownership_state\" = 'AwaitingClaim'\n    AND \"owner_organization_id\" IS NULL\n    AND \"owner_user_id\" IS NULL)\nOR\n(\"ownership_state\" = 'IdentityOwned'\n    AND \"owner_organization_id\" IS NULL\n    AND \"owner_user_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_gift_cards_provenance", "(\"generation\" = 0\n    AND \"source_gift_card_id\" IS NULL\n    AND \"root_gift_card_id\" = \"id\")\nOR\n(\"generation\" > 0\n    AND \"source_gift_card_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_gift_cards_validity", "\"expires_at_utc\" > \"valid_from_utc\"");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", null)
                        .WithMany()
                        .HasForeignKey("SourceGiftCardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
