// <auto-generated />
using System;
using GiftCardPlatform.Modules.GiftCards.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.GiftCards.Infrastructure.Migrations
{
    [DbContext(typeof(GiftCardsDbContext))]
    [Migration("20260802155913_AllowSharedChildOwnershipState")]
    partial class AllowSharedChildOwnershipState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gift_cards")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("business_reference");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DistributedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distributed_at_utc");

                    b.Property<Guid?>("DistributionInvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_invitation_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<decimal>("InitialValue")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("initial_value");

                    b.Property<bool>("IsDivisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_divisible");

                    b.Property<bool>("IsTransferable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_transferable");

                    b.Property<Guid>("IssuanceLedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuance_ledger_transaction_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("IssuedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_membership_id");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<Guid>("IssuingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_organization_id");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid?>("OwnerOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_organization_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("OwnershipState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ownership_state");

                    b.Property<string>("PublicReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("public_reference");

                    b.Property<Guid>("RootGiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_gift_card_id");

                    b.Property<Guid?>("SourceGiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_gift_card_id");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DistributionInvitationId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_distribution_invitation")
                        .HasFilter("\"distribution_invitation_id\" IS NOT NULL");

                    b.HasIndex("IssuanceLedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_issuance_transaction");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_ledger_account");

                    b.HasIndex("PublicReference")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_public_reference");

                    b.HasIndex("SourceGiftCardId")
                        .HasDatabaseName("ix_gift_cards_source")
                        .HasFilter("\"source_gift_card_id\" IS NOT NULL");

                    b.HasIndex("FundingOrganizationId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_cards_tenant_idempotency");

                    b.HasIndex("RootGiftCardId", "Generation")
                        .HasDatabaseName("ix_gift_cards_root_generation");

                    b.HasIndex("OwnerUserId", "IssuedAtUtc", "Id")
                        .HasDatabaseName("ix_gift_cards_identity_owner")
                        .HasFilter("\"owner_user_id\" IS NOT NULL");

                    b.HasIndex("OwnerOrganizationId", "OwnershipState", "IssuedAtUtc", "Id")
                        .HasDatabaseName("ix_gift_cards_organization_inventory");

                    b.ToTable("gift_cards", "gift_cards", t =>
                        {
                            t.HasCheckConstraint("ck_gift_cards_amount", "\"initial_value\" > 0");

                            t.HasCheckConstraint("ck_gift_cards_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_gift_cards_distribution_state", "(\"ownership_state\" = 'OrganizationInventory'\r\n    AND \"lifecycle_state\" IN (\r\n        'Active', 'Suspended', 'Cancelled', 'Expired')\r\n    AND \"distribution_invitation_id\" IS NULL\r\n    AND \"distributed_at_utc\" IS NULL\r\n    AND \"claimed_at_utc\" IS NULL)\r\nOR\r\n(\"ownership_state\" = 'AwaitingClaim'\r\n    AND \"lifecycle_state\" IN (\r\n        'AwaitingClaim', 'Suspended', 'Cancelled', 'Expired')\r\n    AND \"distribution_invitation_id\" IS NOT NULL\r\n    AND \"distributed_at_utc\" IS NOT NULL\r\n    AND \"claimed_at_utc\" IS NULL)\r\nOR\r\n(\"ownership_state\" = 'IdentityOwned'\n    AND \"lifecycle_state\" IN (\n        'Active', 'Suspended', 'Cancelled', 'Expired')\n    AND \"claimed_at_utc\" IS NOT NULL\n    AND (\n        (\"generation\" = 0\n            AND \"distribution_invitation_id\" IS NOT NULL\n            AND \"distributed_at_utc\" IS NOT NULL)\n        OR\n        (\"generation\" > 0\n            AND \"source_gift_card_id\" IS NOT NULL\n            AND \"distribution_invitation_id\" IS NULL\n            AND \"distributed_at_utc\" IS NULL)))");

                            t.HasCheckConstraint("ck_gift_cards_ownership", "(\"ownership_state\" = 'OrganizationInventory'\r\n    AND \"owner_organization_id\" IS NOT NULL\r\n    AND \"owner_user_id\" IS NULL)\r\nOR\r\n(\"ownership_state\" = 'AwaitingClaim'\r\n    AND \"owner_organization_id\" IS NULL\r\n    AND \"owner_user_id\" IS NULL)\r\nOR\r\n(\"ownership_state\" = 'IdentityOwned'\r\n    AND \"owner_organization_id\" IS NULL\r\n    AND \"owner_user_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_gift_cards_provenance", "(\"generation\" = 0\r\n    AND \"source_gift_card_id\" IS NULL\r\n    AND \"root_gift_card_id\" = \"id\")\r\nOR\r\n(\"generation\" > 0\r\n    AND \"source_gift_card_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_gift_cards_validity", "\"expires_at_utc\" > \"valid_from_utc\"");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.GiftCards.Domain.GiftCardLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("IssuingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuing_organization_id");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_state");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_state");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<decimal?>("ReturnedAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("returned_amount");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_card_terminal_lifecycle")
                        .HasFilter("\"action\" IN ('Cancel', 'Expire')");

                    b.HasIndex("LedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_card_lifecycle_ledger_transaction")
                        .HasFilter("\"ledger_transaction_id\" IS NOT NULL");

                    b.HasIndex("GiftCardId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_card_lifecycle_idempotency");

                    b.HasIndex("GiftCardId", "OccurredAtUtc", "Id")
                        .HasDatabaseName("ix_gift_card_lifecycle_history");

                    b.ToTable("lifecycle_events", "gift_cards", t =>
                        {
                            t.HasCheckConstraint("ck_gift_card_lifecycle_event_actor", "(\"actor_type\" = 'OrganizationMember'\r\n    AND \"actor_membership_id\" IS NOT NULL)\r\nOR\r\n(\"actor_type\" <> 'OrganizationMember'\r\n    AND \"actor_membership_id\" IS NULL)");

                            t.HasCheckConstraint("ck_gift_card_lifecycle_event_financial", "(\r\n    \"action\" IN ('Cancel', 'Expire')\r\n    AND \"returned_amount\" IS NOT NULL\r\n    AND \"returned_amount\" >= 0\r\n    AND \"currency\" IS NOT NULL\r\n    AND (\r\n        (\"returned_amount\" = 0\r\n            AND \"ledger_transaction_id\" IS NULL)\r\n        OR\r\n        (\"returned_amount\" > 0\r\n            AND \"ledger_transaction_id\" IS NOT NULL)\r\n    )\r\n)\r\nOR\r\n(\r\n    \"action\" IN ('Suspend', 'Reactivate')\r\n    AND \"returned_amount\" IS NULL\r\n    AND \"currency\" IS NULL\r\n    AND \"ledger_transaction_id\" IS NULL\r\n)");

                            t.HasCheckConstraint("ck_gift_card_lifecycle_event_transition", "(\"action\" = 'Suspend' AND \"new_state\" = 'Suspended')\r\nOR\r\n(\"action\" = 'Reactivate' AND \"new_state\" IN ('Active', 'AwaitingClaim'))\r\nOR\r\n(\"action\" = 'Cancel' AND \"new_state\" = 'Cancelled')\r\nOR\r\n(\"action\" = 'Expire' AND \"new_state\" = 'Expired')");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", null)
                        .WithMany()
                        .HasForeignKey("SourceGiftCardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.GiftCards.Domain.GiftCardLifecycleEvent", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.GiftCards.Domain.GiftCard", null)
                        .WithMany()
                        .HasForeignKey("GiftCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
