<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GiftCardPlatform.BuildingBlocks\GiftCardPlatform.BuildingBlocks.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.Audit.Contracts\GiftCardPlatform.Modules.Audit.Contracts.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.Authorization.Contracts\GiftCardPlatform.Modules.Authorization.Contracts.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.Distribution.Contracts\GiftCardPlatform.Modules.Distribution.Contracts.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.GiftCards.Contracts\GiftCardPlatform.Modules.GiftCards.Contracts.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.Notifications.Contracts\GiftCardPlatform.Modules.Notifications.Contracts.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.Identity.Contracts\GiftCardPlatform.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\GiftCardPlatform.Modules.Partners.Contracts\GiftCardPlatform.Modules.Partners.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
