// <auto-generated />
using System;
using GiftCardPlatform.Modules.Payments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Payments.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PaymentProvision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("confirmed_amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<string>("GiftCardPublicReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gift_card_public_reference");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("PaymentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_token_id");

                    b.Property<Guid>("PosClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_client_id");

                    b.Property<Guid>("PosTerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_terminal_id");

                    b.Property<string>("PosTransactionReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pos_transaction_reference");

                    b.Property<Guid?>("RedemptionLedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("redemption_ledger_transaction_id");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("StoreReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("store_reference");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provisions_token");

                    b.HasIndex("RedemptionLedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_provisions_redemption_transaction")
                        .HasFilter("\"redemption_ledger_transaction_id\" IS NOT NULL");

                    b.HasIndex("GiftCardId", "State")
                        .HasDatabaseName("ix_payment_provisions_card_state");

                    b.HasIndex("State", "ExpiresAtUtc")
                        .HasDatabaseName("ix_payment_provisions_due");

                    b.ToTable("payment_provisions", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_provisions_amount", "\"amount\" > 0 AND \"amount\" <= 1000000000");

                            t.HasCheckConstraint("ck_payment_provisions_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_payment_provisions_settlement", "(\"state\" = 'Active'\n    AND \"settled_at_utc\" IS NULL\n    AND \"confirmed_amount\" IS NULL\n    AND \"redemption_ledger_transaction_id\" IS NULL)\nOR\n(\"state\" = 'Confirmed'\n    AND \"settled_at_utc\" IS NOT NULL\n    AND \"confirmed_amount\" > 0\n    AND \"confirmed_amount\" <= \"amount\"\n    AND \"redemption_ledger_transaction_id\" IS NOT NULL)\nOR\n(\"state\" IN ('Cancelled', 'Expired')\n    AND \"settled_at_utc\" IS NOT NULL\n    AND \"confirmed_amount\" IS NULL\n    AND \"redemption_ledger_transaction_id\" IS NULL)");

                            t.HasCheckConstraint("ck_payment_provisions_window", "\"expires_at_utc\" > \"created_at_utc\"");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PaymentRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<string>("GiftCardPublicReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gift_card_public_reference");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("PaymentProvisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_provision_id");

                    b.Property<Guid>("PosClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_client_id");

                    b.Property<Guid>("PosTerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_terminal_id");

                    b.Property<string>("PosTransactionReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pos_transaction_reference");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RedemptionLedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("redemption_ledger_transaction_id");

                    b.Property<Guid>("RefundLedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_ledger_transaction_id");

                    b.Property<DateTimeOffset>("RefundedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at_utc");

                    b.Property<string>("StoreReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("store_reference");

                    b.HasKey("Id");

                    b.HasIndex("RefundLedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_refunds_ledger_transaction");

                    b.HasIndex("GiftCardId", "RefundedAtUtc")
                        .HasDatabaseName("ix_payment_refunds_card_refunded");

                    b.HasIndex("PaymentProvisionId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_refunds_provision_idempotency");

                    b.ToTable("payment_refunds", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_refunds_amount", "\"amount\" > 0");

                            t.HasCheckConstraint("ck_payment_refunds_currency", "\"currency\" ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PaymentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FundingOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_organization_id");

                    b.Property<Guid>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("NumericCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("numeric_code_hash");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("NumericCodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_tokens_numeric_code_hash")
                        .HasFilter("\"numeric_code_hash\" IS NOT NULL");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_payment_tokens_owner");

                    b.HasIndex("GiftCardId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_payment_tokens_card_expiry");

                    b.ToTable("payment_tokens", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_tokens_consumption", "\"consumed_at_utc\" IS NULL OR \"consumed_at_utc\" >= \"issued_at_utc\"");

                            t.HasCheckConstraint("ck_payment_tokens_expiry", "\"expires_at_utc\" > \"issued_at_utc\"");

                            t.HasCheckConstraint("ck_payment_tokens_numeric_code_hash", "\"numeric_code_hash\" IS NULL OR \"numeric_code_hash\" ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_payment_tokens_secret_hash", "\"secret_hash\" ~ '^[0-9A-F]{64}$'");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PosClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_pos_clients_code");

                    b.ToTable("pos_clients", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_pos_clients_disabled", "(\"status\" = 'Disabled') = (\"disabled_at_utc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_pos_clients_secret_hash", "\"secret_hash\" ~ '^[0-9A-F]{64}$'");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PosTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<Guid>("PosClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("pos_client_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StoreReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("store_reference");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PosClientId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_pos_terminals_client_code");

                    b.ToTable("pos_terminals", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_pos_terminals_disabled", "(\"status\" = 'Disabled') = (\"disabled_at_utc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PaymentRefund", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Payments.Domain.PaymentProvision", null)
                        .WithMany()
                        .HasForeignKey("PaymentProvisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Payments.Domain.PosTerminal", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Payments.Domain.PosClient", null)
                        .WithMany()
                        .HasForeignKey("PosClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
