// <auto-generated />
using System;
using GiftCardPlatform.Modules.CorporateCredits.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.CorporateCredits.Infrastructure.Migrations
{
    [DbContext(typeof(CorporateCreditsDbContext))]
    [Migration("20260727084744_InitialCorporateCredits")]
    partial class InitialCorporateCredits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("corporate_credits")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.CorporateCredits.Domain.CorporateCreditAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AllocatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at_utc");

                    b.Property<Guid>("AllocatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocated_by_user_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("business_reference");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_corporate_credit_allocations_idempotency");

                    b.HasIndex("LedgerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_corporate_credit_allocations_ledger_transaction");

                    b.HasIndex("OrganizationId", "AllocatedAtUtc")
                        .HasDatabaseName("ix_corporate_credit_allocations_organization_allocated");

                    b.ToTable("allocations", "corporate_credits", t =>
                        {
                            t.HasCheckConstraint("ck_corporate_credit_allocations_amount", "\"amount\" > 0");

                            t.HasCheckConstraint("ck_corporate_credit_allocations_currency", "\"currency\" ~ '^[A-Z]{3}$'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
