// <auto-generated />
using System;
using GiftCardPlatform.Modules.Ledger.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftCardPlatform.Modules.Ledger.Infrastructure.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260728054345_AddGiftCardOwnerReadPolicies")]
    partial class AddGiftCardOwnerReadPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ledger")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiftCardPlatform.Modules.Ledger.Domain.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid?>("GiftCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_card_id");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_gift_card_account")
                        .HasFilter("\"gift_card_id\" IS NOT NULL");

                    b.HasIndex("Type", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_platform_account")
                        .HasFilter("\"organization_id\" IS NULL");

                    b.HasIndex("OrganizationId", "Type", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_organization_account")
                        .HasFilter("\"type\" = 'OrganizationCorporateCredit'");

                    b.ToTable("accounts", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_ledger_accounts_scope", "(\"type\" = 'PlatformFunding'\n    AND \"organization_id\" IS NULL\n    AND \"gift_card_id\" IS NULL)\nOR\n(\"type\" = 'OrganizationCorporateCredit'\n    AND \"organization_id\" IS NOT NULL\n    AND \"gift_card_id\" IS NULL)\nOR\n(\"type\" = 'GiftCardValue'\n    AND \"organization_id\" IS NOT NULL\n    AND \"gift_card_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Ledger.Domain.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrganizationId", "AccountId")
                        .HasDatabaseName("ix_ledger_entries_organization_account");

                    b.HasIndex("TransactionId", "Direction")
                        .HasDatabaseName("ix_ledger_entries_transaction_direction");

                    b.ToTable("entries", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount", "\"amount\" > 0");

                            t.HasCheckConstraint("ck_ledger_entries_currency", "\"currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_ledger_entries_direction", "\"direction\" IN ('Debit', 'Credit')");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Ledger.Domain.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("business_reference");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<string>("IntentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("intent_hash")
                        .IsFixedLength();

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_transactions_reversal")
                        .HasFilter("\"reverses_transaction_id\" IS NOT NULL");

                    b.HasIndex("OperationType", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_transactions_operation_idempotency");

                    b.HasIndex("OrganizationId", "PostedAtUtc")
                        .HasDatabaseName("ix_ledger_transactions_organization_posted");

                    b.ToTable("transactions", "ledger", t =>
                        {
                            t.HasCheckConstraint("ck_ledger_transactions_organization", "\"organization_id\" <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Ledger.Domain.LedgerEntry", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Ledger.Domain.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiftCardPlatform.Modules.Ledger.Domain.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Ledger.Domain.LedgerTransaction", b =>
                {
                    b.HasOne("GiftCardPlatform.Modules.Ledger.Domain.LedgerTransaction", null)
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GiftCardPlatform.Modules.Ledger.Domain.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
